### ISSUE TITLE
Suggested Ubuntu package dependencies

### ISSUE THREAD

**Issue by felixduvallet** [mikeferguson/pocketsphinx#10]
I suggest adding the package dependencies required to successfully run the pocketsphinx ros node from source.

Here's a patch to the README.md:

```
diff --git a/README.md b/README.md
index 26c97fb..2405b0c 100644
--- a/README.md
+++ b/README.md
@@ -1 +1,5 @@
 A simple ROS wrapper for using Pocketsphinx (via gstreamer) with ROS. See docs here http://wiki.ros.org/pocketsphinx
+
+Ubuntu package depencies:
+
+    sudo aptitude install gstreamer0.10-pocketsphinx pocketsphinx-lm-en-hub4 pocketsphinx-utils pocketsphinx-hmm-en-hub4wsj
lines 1-16/16 (END)
```

**Comment by mikeferguson** [comment]
There is a dependency on gstreamer0.10-pocketsphinx in the package.xml -- according to http://packages.ubuntu.com/trusty/libs/gstreamer0.10-pocketsphinx, gstreamer0.10-pocketsphinx recommends pocketsphinx-lm-en-hub4 and pocketsphinx-hmm-en-hub4wsj. Finally pocketsphinx-lm-en-hub4 recommends pocketsphinx-utils. Thus, installed gstreamer0.10-pocketsphinx should install all of these packages. And pocketsphinx is released and building on Indigo, so the rosdeps are correct. I just tested installing from debians, and the correct dependencies are all installed.

If you're installing from source, you would of course have to run rosdep to install Ubuntu packages that the package depends on.

**Comment by felixduvallet** [comment]
Thanks for having a look, I'm happy to mark it as resolved if you don't wish to have the package list in the README. I got everything running, but I figured this could help others down the line. At least one other person (#8) had the same problem I had with a missing hub4wsj package (the pocketsphinx runtime error message is not terribly helpful).
In any case, a very nice package. Thanks.

**Comment by mikeferguson** [comment]
https://github.com/mikeferguson/pocketsphinx/commit/d654594451db2b365a4272f86ecf3e39b3df019e
