### ISSUE TITLE
ImportError: No module named pygst

### ISSUE THREAD

**Issue by qinhaojie0721** [mikeferguson/pocketsphinx#13]
jenniful@jenniful-Lenovo:~/catkin_ws$ source ~/catkin_ws/devel/setup.bash
jenniful@jenniful-Lenovo:~/catkin_ws$ rosrun pocketsphinx recognizer.py
Traceback (most recent call last):
  File "/home/jenniful/catkin_ws/src/pocketsphinx/nodes/recognizer.py", line 26, in <module>
    import pygst
ImportError: No module named pygst

I use ubuntu 14.04 python 2.7.6,how to solve this problem about " ImportError: No module named pygst"? Actually, I can't find a module named pygst at python's official website。

**Comment by felixduvallet** [comment]
You are missing dependencies.

```
rosdep install --from-paths pocketsphinx
```

It will ask you to install required packages.

**Comment by qinhaojie0721** [comment]
Thanks a lot,but after I type what you say, it returns #All required rosdeps installed successfully

**Comment by felixduvallet** [comment]
Odd, try the package for your system listed here:
http://rosindex.github.io/d/python-gst/

In any case, this question belongs on answers.ros.org/questions/ and not github.
