### ISSUE TITLE
Training  a dictionary and language model

### ISSUE THREAD

**Issue by TonderaiZR** [mikeferguson/pocketsphinx#14]
Hello

I have pocketsphinx installed on ros but looking to improve the recognition.  I used the IMTool : 
http://www.speech.cs.cmu.edu/tools/lmtool-new.html . I have download the .lm and .dic file
How can I integrate it into my project i.e What folder will the files need to be placed in.

Hope you can help.

Cheers.

**Comment by mikeferguson** [comment]
About to archive this project
