### ISSUE TITLE
voice_cmd.launch error 

### ISSUE THREAD

**Issue by leiw324** [mikeferguson/pocketsphinx#19]
Hello,

**Here is my testing env:**

ROS kinect version

Ubuntu 16.04.5 TLS xenial

VirtualBox 5.2.18

**When type roslaunch pocketsphinx voice_cmd.launch with error:**

wilson@wilson-VirtualBox:~$ roslaunch pocketsphinx voice_cmd.launch ... logging to /home/wilson/.ros/log/1dde0bca-34e1-11e9-95df-080027787a29/roslau nch-wilson-VirtualBox-2200.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wilson-VirtualBox:44835/

# SUMMARY
PARAMETERS

* /recognizer/dict: /home/wilson/catk...
* /recognizer/lm: /home/wilson/catk...
* /rosdistro: kinetic
* /rosversion: 1.12.14

NODES
/
recognizer (pocketsphinx/recognizer.py)
voice_cmd_vel (pocketsphinx/voice_cmd_vel.py)

auto-starting new master
process[master]: started with pid [2211]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1dde0bca-34e1-11e9-95df-080027787a29
process[rosout-1]: started with pid [2224]
started core service [/rosout]
process[recognizer-2]: started with pid [2227]
process[voice_cmd_vel-3]: started with pid [2228]
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
warnings.warn(str(e), _gtk.Warning) /home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/voice_cmd_vel.py:24: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information. self.pub_ = rospy.Publisher('cmd_vel', Twist)
/home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py:68: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
self.pub = rospy.Publisher('~output', String)
Traceback (most recent call last):
File "/home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py", line 177, in 
start = recognizer()
File "/home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py", line 73, in **init**
self.start_recognizer()
File "/home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py", line 80, in start_recognizer
self.pipeline = gst.parse_launch(self.launch_config)
glib.GError: no element "gconfaudiosrc"
Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 466, in signal_shutdown
h()
File "/home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py", line 131, in shutdown
gtk.main_quit()
RuntimeError: called outside of a mainloop
[recognizer-2] process has died [pid 2227, exit code 1, cmd /home/wilson/catkin_ws/src/pocketsphinx/0.4/nodes/recognizer.py __name:=recognizer __log:=/home/wilson/.ros/log/1dde0bca-34e1-11e9-95df-080027787a29/recognizer-2.log].
log file: /home/wilson/.ros/log/1dde0bca-34e1-11e9-95df-080027787a29/recognizer-2*.log

**Here is recognizer-2.log**

[rospy.client][INFO] 2019-02-20 15:28:34,170: init_node, name[/recognizer], pid[2227]
[xmlrpc][INFO] 2019-02-20 15:28:34,171: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-02-20 15:28:34,171: Started XML-RPC server [http://wilson-VirtualBox:45971/]
[rospy.init][INFO] 2019-02-20 15:28:34,172: ROS Slave URI: [http://wilson-VirtualBox:45971/]
[rospy.impl.masterslave][INFO] 2019-02-20 15:28:34,172: _ready: http://wilson-VirtualBox:45971/
[xmlrpc][INFO] 2019-02-20 15:28:34,172: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-02-20 15:28:34,173: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-02-20 15:28:34,272: registered with master
[rospy.rosout][INFO] 2019-02-20 15:28:34,273: initializing /rosout core topic
[rospy.rosout][INFO] 2019-02-20 15:28:34,285: connected to core topic /rosout
[rospy.simtime][INFO] 2019-02-20 15:28:34,293: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-02-20 15:28:34,316: Launch config: gconfaudiosrc
[rosout][INFO] 2019-02-20 15:28:34,336: Starting recognizer...
[rospy.core][INFO] 2019-02-20 15:28:34,343: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2019-02-20 15:28:34,361: atexit

Thanks

**Comment by yerongguang** [comment]
glib.GError: no element "gconfaudiosrc"怎么解决的啊

**Comment by mikeferguson** [comment]
About to archive this project
