### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by olmerg** [mikeferguson/pocketsphinx#20]
this package do not work in melodic because ubuntu 18.04 use gstreamer1.0 and not 0.1

**Comment by mikeferguson** [comment]
ros1 branch works with noetic, a few things are needed to work with Melodic:

 * We need to setup the shebangs for py2/3: https://github.com/ros/ros_comm/issues/1832
 * Need to figure out why it is crashinig on melodic (segmentation fault inside gstreamer it appears)

**Comment by roboav8r** [comment]
Has anyone tried a Python 3 virtual environment within 18.04/Melodic?
If not, I will give this a try.

Edit: Tried this using 18.04/Melodic and a Python3 virtual environment and still getting the segmentation fault.

**Comment by mikeferguson** [comment]
About to archive this project
