### ISSUE TITLE
pocketsphinx plugin for GStreamer1.0 under ROS/kinetic

### ISSUE THREAD

**Issue by pbomel** [mikeferguson/pocketsphinx#22]
Hi Mike, this is the first time I'm creating an issue :-)
I've made the port of your ROS/Jade pocketsphinx package on ROS/kinetic.
There is a new recognizer.py file + some docs about the necessary linux libs to install.
I've tested it with ROS1 and python2.7.
Should work with python3.5+, so may be "straight right" with ROS 2.
Tell me what to do to in order to make that port available to all.
We'd like to show that this work has been done at a research lab (LabSTICC, https://www.labsticc.fr) in collaboration with an engineering school (ENSIBS, https://www-ensibs.univ-ubs.fr), of a French University (Université de Bretagne Sud, Lorient, France, https://www.univ-ubs.fr). Is this possible ?

**Comment by mikeferguson** [comment]
So opening a pull request with your changes is the first step. Fork this repo, add your changes, open a pull request. I just created a new "master" branch - target that with your PR.

As for the attribution - you can add that to the copyright holders at the top of each file you edit, or you could add it to the README. Your commit(s) will of course also be in the history.

**Comment by mikeferguson** [comment]
Closing due to no response. I recently merged a PR which gave gstreamer1.0 and python3 support
