### ISSUE TITLE
Custom LM and Dict not working

### ISSUE THREAD

**Issue by roboav8r** [mikeferguson/pocketsphinx#24]
Hi all,

**What I did:**
- Created a custom language model and dictionary for a few simple command tasks. I also made a launch file that sets the ```~lm``` and ```~dict``` parameters according to the file names and locations.
- Made one minor change to ```recognizer.py```: I changed the ```python3``` shebang to ```python```, since I am working on ROS Melodic.
- Installed ```pocketsphinx-en-us``` using ```apt-get``` (I was getting a segfault error before I did this)

**What's happening:**
The recognizer recognizes a lot of phrases that aren't in the dictionary or LM, and the accuracy is pretty low. I don't think this is expected and I believe it's using the installed ```pocketsphinx-en-us``` model instead of the smaller one that I made.

For this application I really only need a few phrases, but they need to be recognized accurately. Do you all have any recommendations for why my custom LM and Dict might not be working? 

Thanks!

**Comment by roboav8r** [comment]
Alternatively, is there a version/tag of ```pocketsphinx``` for Melodic that I could try?

**Comment by mikeferguson** [comment]
> Alternatively, is there a version/tag of `pocketsphinx` for Melodic that I could try?

There is a ticket here: https://github.com/mikeferguson/pocketsphinx/issues/20 - I've never figured out why things did not work on 18.04 but did work on 20.04.

**Comment by roboav8r** [comment]
Thanks @mikeferguson, it works when I switched back to Noetic.
