### ISSUE TITLE
ROS PocketSphinix on ROS Noetic

### ISSUE THREAD

**Issue by therobocademy** [mikeferguson/pocketsphinx#27]
I have tried to set this package in ROS Noetic and installed the following dependencies to make it work. If you are not installing any of these packages, the node will crash or not respond to your voice commands.

```
sudo apt install gstreamer1.0-pocketsphinx pocketsphinx pocketsphinx-en-us python3-pocketsphinx
```

**Comment by mikeferguson** [comment]
About to archive this project
