### ISSUE TITLE
ubuntu20.04 noetic no element "pocketsphinx" (1)

### ISSUE THREAD

**Issue by zhwang026** [mikeferguson/pocketsphinx#28]
hi, when i run robocup.launch in the first time with: roslaunch pocketsphinx robocup.launch

the error shows:
... logging to /home/zhw/.ros/log/48fd9be4-94d7-11ee-b17d-e72f1e9561da/roslaunch-zhw-System-6850.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zhw-System:38047/

SUMMARY
========

PARAMETERS
 * /recognizer/dict: /home/zhw/pocketp...
 * /recognizer/lm: /home/zhw/pocketp...
 * /recognizer/mic_name: alsa_output.pci-0...
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    recognizer (pocketsphinx/recognizer.py)

auto-starting new master
process[master]: started with pid [6877]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 48fd9be4-94d7-11ee-b17d-e72f1e9561da
process[rosout-1]: started with pid [6907]
started core service [/rosout]
process[recognizer-2]: started with pid [6910]
[INFO] [1701936286.532727]: Using: pulsesrc device=2 name=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
[INFO] [1701936286.535277]: Launch config: pulsesrc device=2
[INFO] [1701936286.544215]: Starting recognizer... 
Traceback (most recent call last):
  File "/home/zhw/pocketphinx_ws/src/pocketsphinx-ros1/nodes/recognizer.py", line 178, in <module>
    start = recognizer()
  File "/home/zhw/pocketphinx_ws/src/pocketsphinx-ros1/nodes/recognizer.py", line 82, in __init__
    self.start_recognizer()
  File "/home/zhw/pocketphinx_ws/src/pocketsphinx-ros1/nodes/recognizer.py", line 89, in start_recognizer
    self.pipeline = gst.parse_launch(self.launch_config)
gi.repository.GLib.Error: gst_parse_error: no element "pocketsphinx" (1)

(python3:6910): Gtk-CRITICAL **: 16:04:46.585: gtk_main_quit: assertion 'main_loops != NULL' failed

I installed gstreamer1.0-pocketsphinx with "sudo apt-get install gstreamer1.0-pocketsphinx"
if someone can help me with that, I'll be grateful!!

**Comment by mikeferguson** [comment]
About to archive this project
