### ISSUE TITLE
Multiple alsasrc's

### ISSUE THREAD

**Issue by jdddog** [mikeferguson/pocketsphinx#6]
I've got some additions I'll contribute that let you run multiple recognizers at once and change the lm and dic files on the fly via ros services.

However, I can't seem to connect to two alsa devices at once with gstreamer?

E.g. in one node you specify the gstreamer config as:

alsasrc device=hw:0 ! audioconvert ! audioresample ! vader name=vad auto-threshold=true ! pocketsphinx name=asr ! fakesink'

This runs fine. But if I start another node, with a gstreamer config that points to a different alsasrc, e.g.

alsasrc device=hw:1 ! audioconvert ! audioresample ! vader name=vad auto-threshold=true ! pocketsphinx name=asr ! fakesink'

The second one wont connect to the alsasrc, because no sound gets sent to the recognizer. 

However, if I leave the second configuration as:

gconfaudiosrc ! audioconvert ! audioresample ! vader name=vad auto-threshold=true ! pocketsphinx name=asr ! fakesink'

It will work, and audio will be sent to both recognizers.

Any ideas why this would occur?

**Comment by mikeferguson** [comment]
I'm actually not all that familiar with gstreamer details, I basically learned enough to implement this package, and that was a couple years ago. Perhaps a gstreamer message board or mailing list could help with this issue.

**Comment by jdddog** [comment]
Ok thanks, yeah I'll give one of those a try.

**Comment by mikeferguson** [comment]
Does #7 address this?

**Comment by jdddog** [comment]
Yeah I used pulsesrc instead and it works fine. Thanks for merging it :)
